global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
    - targets: ['172.31.59.64:8080']
